### ISSUE TITLE
Ad is still not being recognized as viewable 

### ISSUE THREAD

**Issue by kristysk** [googleads/googleads-viewability-insights-extension#3]
**Describe the bug**
When the first ad slot loads to the page, the viewable box does is not viewed as there's a video anchor type unit on the bottom right. However, I noticed that even when the video is below the ad and the ad is completely in view, it is still showing up as non-viewable. 

**To Reproduce**
1. Go to 'https://www.univision.com/noticias/estados-unidos/sentencias-proud-boys-asalto-capitolio-6-enero'
3. Scroll down to past the ad unit until the bottom right video player does not cover the ad
4. See that the box remains red and viewability remains at 0

**Expected behavior**
Once the full ad is view, I would expect the box to change to green and for the ad to have a max viewability of 100. 

**Screenshots**
<img width="1431" alt="Screenshot 2023-10-03 at 4 52 37 PM" src="https://github.com/googleads/googleads-viewability-insights-extension/assets/25311358/6ee001d0-279a-4513-9d23-79bd802406c8">
<img width="1433" alt="Screenshot 2023-10-03 at 4 52 31 PM" src="https://github.com/googleads/googleads-viewability-insights-extension/assets/25311358/1e2ef52a-aeae-43ab-a5f0-af8d44e72a89">
<img width="1433" alt="Screenshot 2023-10-03 at 4 55 37 PM" src="https://github.com/googleads/googleads-viewability-insights-extension/assets/25311358/9383fdef-8ab7-475f-81a2-e79cc669931f">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 117.0.5938.92

**Smartphone (please complete the following information):**

**Additional context**
I can send you the debugr as well.

**Comment by MarkusBordihn** [comment]
Thank you for your report. Upon investigation, it appears that there is no issue with the Chrome extension itself.

Unfortunately I'm unable to reproduce the issue with the provided Test URL. See:
![image](https://github.com/googleads/googleads-viewability-insights-extension/assets/12183293/0b23316e-c340-42ba-a876-4068adeea7dd)

Please note that our support is dedicated solely to addressing issues related specifically to the Chrome extension itself. 
We are unable to troubleshoot individual cases that do not involve a bug or problem directly associated with the extension.

Regarding your viewability concerns, kindly be informed that the extension utilizes events from the GPT library and does not independently measure viewability. Consequently, if an ad or ad slot is reported as non-viewable, it is highly probable that this is not a bug or problem originating from the extension.

For specific viewability issues, we recommend contacting your corresponding support teams / publisher support teams.

**Comment by kristysk** [comment]
Hi Markus,

Appreciate the feedback. I had filed this bug as I thought there was an
issue with the extension recognizing the ad that was viewable. It seems
like it happens on that specific ad that's expandable and the 728x90s are
recognized as expected.

If there is no bug with the extension, then we're good to close here and
I'll look into other things to help determine if the ad is viewable even
though the tool marks it as not viewable.

Appreciate your help here!
